apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-stgf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-stgf
    app.kubernetes.io/part-of: test-app-hbal
  name: test-component-stgf
  namespace: build-e2e-fqpi-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-stgf
status:
  loadBalancer: {}
